---
output: 
 bookdown::word_document2: default
params:
  title: "title"
  author: "author"
  start.date: "start.date"
  end.date: "end.date"
  dac: "DAC"
  total.number.of.dars: "total.number.of.dars"
  total.number.of.projects: "total.number.of.projects"
  num.dars.in.window: "num.dars.in.window"
  number.of.accepted: "number.of.accepted"
  number.of.rejected: "number.of.rejected"
  avg.final: "avg.final"
  avg.accept: "avg.accept"
  avg.reject: "avg.reject"
--- 

---
title: `r params$title`
author: `r params$author`
date: `r format(Sys.time(), '%d %B, %Y')`
---

The `r params$dac` Data Access Committee (DAC) currently manages `r params$total.number.of.dars` data access requests (DARs) for access to `r params$total.number.of.projects` projects in dbGaP.  

# Data Access Requests
Between `r params$start.date` and `r params$end.date` the DAC reviewed `r params$num.dars.in.window` DARs. Of these, `r params$number.of.accepted` were accepted while `r params$number.of.rejected` were rejected.  The average amount of time from when the Principle Investigator (PI) submited a DAR to the final decision by the DAC was `r params$avg.final` days.  The average time to an accepted decision was `r params$avg.accept` days, while the average time to a rejected decision was `r params$avg.reject` days.  Figure \@ref(fig:compline) is a barplot comparing the `r params$dac` DAC to time to final decision to the average across all NIH DACs during the same time interval.  

```{r compline, fig.cap="Comparison of Time to Final Decision", echo=FALSE}
par(mar = c(4, 4, .2, .1))
plot(1:4) #call data and plot here
```

# Study Registrations


This report was prepared using the DACReportingTool package for R, build 0.0.1 by Mr. Hoyin Chu and Dr. Christopher Steven Marcum. 
